config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

resources :books, only: [:new, :create, :index, :show, :edit, :destroy]
resources :users, only: [:index, :show, :update, :edit]

get "home/about" => "home#about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def destroy
  end

  def edit
  end




   private

  def book_params
    params.require(:book).permit(:title, :caption)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @book = Book
  end

  def update
  end

  def edit
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>welcome to Bookers !!</h1>

<p>In Bookers,</p>

<p>you can share and exchange your opinions , inpressions , and emotions<br>

about various books!</p>



<%= link_to "log In", new_user_session_path %>
<%= link_to "Sign Up", new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="header-logo">
       <%= link_to "Bookers", root_path %>
     </div>


     <% if user_signed_in? %>
      <li>
        <%= link_to "home", user_path(current_user.id) %>
      </li>
      <li>
       <%= link_to "users", users_path  %>
      </li>
      <li>
       <%= link_to "Bookes", books_path   %>
      </li>
      <li>
        <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
       <%= link_to "Home", root_path %>
      </li>
      <li>
       <%= link_to "About", home_about_path %>
      </li>
      <li>
       <%= link_to "sign up", new_user_registration_path %>
      </li>

      <li>
        <%= link_to "LogIn", new_user_session_path %>
      </li>
    <% end %>



    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="header">Books</div>

<table>
  <thead>
    <th>Title</th>
    <th>Opinion</th>
  </thead>
  <tbody>
    <th><%= @book.title %></th>
    <th><%= @book.caption %></th>
  </tbody>
</table>